import { PlayerStatus } from '../enums/index.js';
import { ICharacter } from './character.interface.js';
import { IGuildMember } from './guild.interface.js';
import { IFriend } from './social.interface.js';
import { IAchievement } from './achievement.interface.js';
import { ISettings } from './settings.interface.js';
import { ICurrency } from './economy.interface.js';
import { ITitle } from './achievement.interface.js';
import { IMount } from './mount.interface.js';
import { IPet } from './pet.interface.js';
import { IStatistics } from './statistics.interface.js';

export interface IPlayer {
  id: string;
  accountId: string;
  username: string;
  email: string;
  status: PlayerStatus;
  characters: ICharacter[];
  selectedCharacterId?: string;
  friends: IFriend[];
  blockedPlayers: string[];
  achievements: IAchievement[];
  unlockedTitles: ITitle[];
  selectedTitle?: ITitle;
  accountCurrency: ICurrency[];
  premiumCurrency: number;
  collectibles: {
    mounts: IMount[];
    pets: IPet[];
    toys: string[];
    transmogs: string[];
  };
  settings: ISettings;
  statistics: IStatistics;
  playtime: number;
  lastLogin: Date;
  createdAt: Date;
  updatedAt: Date;
  isPremium: boolean;
  premiumExpiresAt?: Date;
  isBanned: boolean;
  banReason?: string;
  banExpiresAt?: Date;
  isVerified: boolean;
  twoFactorEnabled: boolean;
  parentalControlsEnabled: boolean;
  ageRestricted: boolean;
  region: string;
  language: string;
  timezone: string;
  referralCode: string;
  referredBy?: string;
  referralRewards: string[];
  loyaltyPoints: number;
  loyaltyTier: number;
  seasonPass?: {
    id: string;
    level: number;
    experience: number;
    claimedRewards: string[];
    purchasedPremium: boolean;
  };
  dailyRewards: {
    lastClaimed: Date;
    streak: number;
    multiplier: number;
  };
  vipLevel: number;
  vipExperience: number;
  vipBenefits: string[];
  subscriptions: {
    type: string;
    startDate: Date;
    endDate: Date;
    autoRenew: boolean;
  }[];
  purchases: {
    id: string;
    itemId: string;
    amount: number;
    currency: string;
    timestamp: Date;
  }[];
  giftsSent: string[];
  giftsReceived: string[];
  supportTickets: string[];
  warnings: {
    reason: string;
    timestamp: Date;
    moderator: string;
  }[];
  commendations: number;
  reports: number;
  socialScore: number;
  contentCreator: boolean;
  streamingEnabled: boolean;
  broadcastSettings: {
    platform: string;
    channelUrl: string;
    autoShare: boolean;
  };
  marketplaceListings: string[];
  tradingPostReputation: number;
  craftingLicenses: string[];
  unlockedContent: string[];
  betaAccess: boolean;
  alphaAccess: boolean;
  foundersPackTier?: number;
  legacyPlayer: boolean;
  migrationCompleted: boolean;
  crossPlatformEnabled: boolean;
  linkedAccounts: {
    platform: string;
    id: string;
    username: string;
  }[];
  cloudSaveEnabled: boolean;
  lastCloudSync: Date;
  personalizedOffers: string[];
  surveyParticipation: string[];
  eventParticipation: string[];
  tournamentHistory: string[];
  specialBadges: string[];
  memorableMonents: {
    type: string;
    description: string;
    timestamp: Date;
    screenshotUrl?: string;
  }[];
  customEmotes: string[];
  voicePackId?: string;
  announcerPackId?: string;
  musicPackId?: string;
  interfaceThemeId?: string;
  cursorPackId?: string;
  loadingScreens: string[];
  selectedLoadingScreen?: string;
  nameplateStyle?: string;
  portraitFrameId?: string;
  chatBadges: string[];
  specialPrivileges: string[];
  earlyAccessFeatures: string[];
  experimentalFeatures: string[];
  optedInBetas: string[];
  feedbackSubmissions: number;
  bugReportsSubmitted: number;
  contributorLevel: number;
  communityReputation: number;
  mentorStatus: boolean;
  mentorRating?: number;
  mentorshipsSCompleted: number;
  guidesWritten: string[];
  videosCreated: string[];
  artworkSubmitted: string[];
  modEndorsements: string[];
  workshopCreations: string[];
  apiKeys: {
    key: string;
    name: string;
    permissions: string[];
    createdAt: Date;
    lastUsed?: Date;
  }[];
  webhooks: {
    url: string;
    events: string[];
    active: boolean;
  }[];
  automationRules: {
    trigger: string;
    action: string;
    conditions: any;
    enabled: boolean;
  }[];
  macros: {
    name: string;
    icon: string;
    commands: string[];
    keybind?: string;
  }[];
  savedLayouts: {
    name: string;
    type: string;
    data: any;
  }[];
  bookmarks: {
    type: string;
    targetId: string;
    name: string;
    timestamp: Date;
  }[];
  notes: {
    id: string;
    title: string;
    content: string;
    tags: string[];
    createdAt: Date;
    updatedAt: Date;
  }[];
  reminders: {
    id: string;
    message: string;
    triggerAt: Date;
    recurring?: string;
    completed: boolean;
  }[];
  goals: {
    id: string;
    type: string;
    target: any;
    progress: any;
    deadline?: Date;
    reward?: string;
  }[];
  wishlists: {
    items: string[];
    mounts: string[];
    pets: string[];
    transmogs: string[];
    other: string[];
  };
  blacklist: {
    players: string[];
    guilds: string[];
    items: string[];
    zones: string[];
  };
  preferences: {
    autoAcceptQuests: boolean;
    autoTurnInQuests: boolean;
    autoLoot: boolean;
    autoRepair: boolean;
    autoSell: string[];
    autoBuy: string[];
    autoDisenchant: string[];
    smartCasting: boolean;
    actionCombat: boolean;
    showDamageNumbers: boolean;
    showHealingNumbers: boolean;
    condensedBuffs: boolean;
    raidFrameStyle: string;
    nameplateMode: string;
    minimapSize: number;
    questTrackerPosition: string;
    chatTabConfiguration: any;
    soundPacks: string[];
    voiceActing: boolean;
    subtitles: boolean;
    colorblindMode?: string;
    reducedMotion: boolean;
    screenReaderEnabled: boolean;
    hapticFeedback: boolean;
    controllerVibration: boolean;
    customKeybinds: any;
    customMacros: any;
  };
  analytics: {
    totalDamageDealt: bigint;
    totalDamageTaken: bigint;
    totalHealingDone: bigint;
    totalHealingReceived: bigint;
    pvpKills: number;
    pvpDeaths: number;
    pvpAssists: number;
    pveKills: number;
    pveDeaths: number;
    questsCompleted: number;
    dungeonsCompleted: number;
    raidsCompleted: number;
    battlegroundsWon: number;
    arenasWon: number;
    itemsLooted: number;
    itemsCrafted: number;
    goldEarned: bigint;
    goldSpent: bigint;
    travelDistance: number;
    jumps: number;
    emotes: number;
    messagesChat: number;
    friendsAdded: number;
    guildsJoined: number;
    achievementPoints: number;
    collectiblesFound: number;
    secretsDiscovered: number;
    worldFirsts: string[];
    serverFirsts: string[];
    rareEncounters: string[];
    epicMoments: string[];
  };
  sessionData: {
    loginTime: Date;
    loginLocation: string;
    loginDevice: string;
    currentZone?: string;
    currentActivity?: string;
    afkTime: number;
    combatTime: number;
    idleWarning: boolean;
  };
  security: {
    lastPasswordChange: Date;
    lastEmailChange?: Date;
    securityQuestions: boolean;
    loginAlerts: boolean;
    unusualActivityDetected: boolean;
    vpnAllowed: boolean;
    trustedDevices: string[];
    loginHistory: {
      timestamp: Date;
      ip: string;
      location: string;
      device: string;
      success: boolean;
    }[];
  };
}